# Generated by Django 4.1.6 on 2023-05-28 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_remove_order_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jumlah',
            field=models.IntegerField(verbose_name='jumlah tiket'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
