# Generated by Django 4.1.6 on 2023-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_jumlah_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
